---
- name: Verify host is in 'workers' or 'controls' group
  ansible.builtin.assert:
    that:
      - inventory_hostname in groups['workers'] or inventory_hostname in groups['controls'] or inventory_hostname in groups['test']
    fail_msg: "Host {{ inventory_hostname }} is not in 'workers' or 'controls' groups"

- name: Install ELRepo GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "https://www.elrepo.org/RPM-GPG-KEY-elrepo.org"

- name: Install ELRepo repository
  ansible.builtin.dnf:
    name: "https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm"
    disable_gpg_check: yes  # Временное отключение проверки для установки
    state: present
  notify: Update DNF cache

- name: Install kernel-ml
  ansible.builtin.dnf:
    name: "kernel-ml"
    enablerepo: elrepo-kernel
    state: latest
  register: kernel_install
  notify: Update GRUB

- name: Verify ELRepo is enabled
  ansible.builtin.command: dnf repolist enabled | grep elrepo
  register: elrepo_check
  failed_when: elrepo_check.rc != 0 and elrepo_check.rc != 1