---
- name: Verify kernel version
  ansible.builtin.command: uname -r
  register: kernel_version
  changed_when: false

- name: Verify cgroup v2
  ansible.builtin.command: stat -fc %T /sys/fs/cgroup/
  register: cgroup_fs
  changed_when: false

- name: Show results
  ansible.builtin.debug:
    msg: |
      Kernel: {{ kernel_version.stdout }}
      CGroup FS: {{ cgroup_fs.stdout }}
      Expected: 'cgroup2fs'