---
- hosts: all
  roles:
    - prepare

- name: Kernel version check and upgrade
  hosts: workers:controls
  gather_facts: true
  tasks:
    - name: Get major kernel version
      ansible.builtin.set_fact:
        kernel_major: "{{ ansible_kernel.split('.')[0]|int }}"

    - name: Apply kernel upgrade if needed
      ansible.builtin.include_role:
        name: upgrade-kernel
      when: kernel_major < 5
      tags: kernel_upgrade

- name: Post-reboot checks
  hosts: workers:controls
  gather_facts: true
  tasks:
    - name: Verify new kernel version
      ansible.builtin.include_role:
        name: upgrade-kernel
        tasks_from: post_reboot.yml
      when: ansible_kernel is version('5.0', '<')  # На случай если обновление не сработало
      tags: post_reboot