---
- hosts: all
  roles:
    - prepare

- name: Apply kernel upgrade to workers and controls
  hosts: workers:controls
  gather_facts: true  # Включаем сбор фактов для получения версии ядра

  tasks:
    - name: Set kernel major version fact
      ansible.builtin.set_fact:
        kernel_major: "{{ ansible_kernel.split('.')[0] | int }}"  # Явное преобразование в integer

    - name: Apply kernel upgrade (only if kernel < 5)
      ansible.builtin.include_role:
        name: upgrade-kernel
      when: kernel_major | int < 5  # Явное преобразование перед сравнением
      tags: kernel_upgrade

- name: Post-reboot verification
  hosts: workers:controls
  gather_facts: true

  tasks:
    - name: Include post-reboot checks
      ansible.builtin.include_role:
        name: upgrade-kernel
        tasks_from: post_reboot.yml
      when: ansible_kernel is version('5.0', '<')  # Альтернативный способ проверки
      tags: post_reboot